version: '3'
services:
    tmp_name:
        image: tmp_name:latest
        build: ./
        container_name: "tmp_name"
        hostname: tmp_name
        privileged: true
        stdin_open: true
        tty: true
        restart: on-failure
        working_dir: /workspace
        entrypoint:
            - /bin/bash
        network_mode: "host"
        extra_hosts:
            - "tmp_domain:192.168.1.10"
        devices:
            - "/tmp/.X11-unix:/tmp/.X11-unix"
        environment:
            - "DISPLAY=:0"
        volumes:
            - "../:/workspace"
